import User from "./page";

export const Users: User[] = [
  {
    userType: "General Fitness",
    firstName: "A",
    lastName: "AL",
    gender: "Male",
    weight: 60,
    height: 1.8,
    dob: "10/7/2024",
    dietType: "Veg",
  },
  {
    userType: "Muscle Up",
    firstName: "B",
    lastName: "BL",
    gender: "Male",
    weight: 60,
    height: 1.8,
    dob: "10/7/2024",
    dietType: "Veg",
  },
  {
    userType: "Weight Loss",
    firstName: "C",
    lastName: "CL",
    gender: "Female",
    weight: 60,
    height: 1.8,
    dob: "10/7/2024",
    dietType: "Veg",
  },
  {
    userType: "Weight Gain",
    firstName: "D",
    lastName: "DL",
    gender: "Male",
    weight: 60,
    height: 1.8,
    dob: "10/7/2024",
    dietType: "Veg",
  },
  {
    userType: "Pregnant Mother",
    firstName: "E",
    lastName: "EL",
    gender: "Female",
    weight: 60,
    height: 1.8,
    dob: "10/7/2024",
    dietType: "Veg",
  },
  {
    userType: "Infant",
    firstName: "F",
    lastName: "FL",
    gender: "Male",
    weight: 60,
    height: 1.8,
    dob: "10/7/2024",
    dietType: "Veg",
  },
];